defaults: &defaults
  environment:
    OPAMVERBOSE: 1
    OPAMWITHTEST: true
    OPAMYES: true
    TERM: xterm
  steps:
  - checkout
  - run:
      name: Configure environment
      command: echo . ~/.profile >> $BASH_ENV
  - run:
      name: Install dependencies
      command: opam install --deps-only .
  - run: 
      name: List installed packages
      command: opam list
  - run:
      name: Build, test, and install package
      command: opam install .
  - run:
      name: Uninstall package
      command: opam uninstall .
  - run:
      name: Build and test locally
      command: make
  - run:
      name: Cleanup local directory
      command: |
        make clean
        ls -AR

jobs:
  coq.8.8:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.8
  coq.8.9:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.9
  coq.8.10:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.10
  coq.dev:
    <<: *defaults
    docker:
    - image: coqorg/coq:dev

workflows:
  version: 2
  build:
    jobs:
    - coq.8.8
    - coq.8.9
    - coq.8.10
    - coq.dev
